### ISSUE TITLE
Mark feature is not applied sometimes

### ISSUE THREAD

**Issue by khaledhosny** [devongovett/fontkit#102]
Testing with [Amir](https://github.com/alif-type/amiri/blob/master/amiri-regular.ttf) font, I noticed that the mark feature is not applied for glyphs inserted by one to many lookup, e,g. in the word `الله`, while they are positioned fine when part of the input text in `اللّٰه`. The two words below should render the same:
![image](https://cloud.githubusercontent.com/assets/93914/26660764/baa665f0-4682-11e7-849e-4cff2ccf563d.png)

**Comment by khaledhosny** [comment]
This might be a font bug, since my lookup was also inserting a zero-width non-mark glyph between the marks and the base, changing it to have a mark glyph class fixes the positioning. Nevertheless HarfBuzz and Uniscribe get the positioning right in either case.

OK, I think I found the real issue, this is related to how HarfBuzz/Unsiscribe attach marks to glyphs resulting from one to many lookups; they will attach the marks to the first glyph (the right most in Arabic) while fontkit seems to be attaching them to the last glyph. Here is another string that is not a font bug `لَكنت`, in fontkit:
![fontkit](https://cloud.githubusercontent.com/assets/93914/26724515/884df26e-47a2-11e7-97a7-713752431b86.png)

compared to HarfBuzz:
![harfbuzz](https://cloud.githubusercontent.com/assets/93914/26724518/8dd1834a-47a2-11e7-82cd-3acc937ab7a5.png)

For more context, see this mailing list thread: https://lists.freedesktop.org/archives/harfbuzz/2012-May/001922.html

**Comment by devongovett** [comment]
Thanks for investigating this. I'll fix it soon. I think we should try to match Harfbuzz and Uniscribe as much as possible.

**Comment by devongovett** [comment]
Fixed by 6586eb938b57a6ddce392218e1d1e87df51a9cbb. Released in v1.7.3, and updated the demo site. Thanks again for reporting!

**Comment by khaledhosny** [comment]
This does not seem to be fixed, `لَكنت` still gives me:
![لَكنت](https://cloud.githubusercontent.com/assets/93914/26758373/a22ac174-48e4-11e7-818c-aa905bd4e89e.png)

(note that the original issue with `الله` is fixed in the font as of https://github.com/alif-type/amiri/commit/42724b3d689a370afe66ae753193a05490776251, but the other issue remains).

**Comment by devongovett** [comment]
Ah, thanks. That one was a separate issue where attached marks were not repositioned if their base glyphs were adjusted in a later lookup. Should be fixed by f344740cef0da77fb5fdf70a1719a9a835af39ad.

**Comment by khaledhosny** [comment]
Thanks, looks good now.
